Update onPushMaster.yaml

diff --git a/.github/workflows/onPushMaster.yaml b/.github/workflows/onPushMaster.yaml
--- a/.github/workflows/onPushMaster.yaml
+++ b/.github/workflows/onPushMaster.yaml
@@ -47,13 +47,20 @@ jobs:
 
     - name: Trigger Template NuGet Package Update Event
       env:
-        TOKEN: ${{ secrets.DISPATCH_TOKE }} 
+        TOKEN: ${{ secrets.DISPATCH_TOKEN }}
       run: |
-        curl -L \
+        response=$(curl -L -o /dev/null -s -w "%{http_code}" \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer $TOKEN" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/LiquidVisions/LiquidVisions.PanthaRhei.Templates/dispatches \
-        -d '{"event_type":"nuget-package-update","client_payload":{"unit":false,"integration":true}}'
+        -d '{"event_type":"nuget-package-update","client_payload":{"unit":false,"integration":true}}')
+        
+        if [ "$response" -ne 200 ]; then
+          echo "Request failed with status code $response"
+          exit 1
+        else
+          echo "Request succeeded with status code $response"
+        fi
       shell: bash
